package com.sourcelens;

import com.sourcelens.module.execution.dto.ExecutionPlanStep;
import com.sourcelens.module.execution.dto.ExecutionResumeState;
import com.sourcelens.module.execution.dto.ExecutionWorkflowPlan;
import com.sourcelens.module.execution.mapper.ExecutionCheckpointStore;
import com.sourcelens.module.execution.service.ExecutionCheckpointIntegrityException;
import com.sourcelens.module.execution.service.ExecutionCheckpointService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.aop.support.AopUtils;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import javax.sql.DataSource;
import java.sql.Connection;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ExecutionCheckpointH2IntegrationTest {

    private DataSource dataSource;
    private JdbcTemplate jdbcTemplate;
    private AnnotationConfigApplicationContext context;
    private ExecutionCheckpointService service;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:p3_checkpoint_" + UUID.randomUUID() + ";MODE=MYSQL;DB_CLOSE_DELAY=-1",
                "sa", ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                create table execution_tasks (
                    id bigint generated by default as identity primary key,
                    status varchar(20) not null
                )
                """);
        try (Connection connection = dataSource.getConnection()) {
            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V033__add_execution_checkpoints.sql"));
        }
        jdbcTemplate.update("insert into execution_tasks (id, status) values (?, ?)", 41L, "RUNNING");
        context = openContext(dataSource);
        service = context.getBean(ExecutionCheckpointService.class);
        assertTrue(AopUtils.isAopProxy(service), "测试必须通过 Spring 事务代理调用生产服务");
    }

    @AfterEach
    void tearDown() {
        if (context != null) {
            context.close();
        }
    }

    @Test
    void restartedTransactionalService_shouldRestoreExactStateAndRejectTailTruncation() {
        ExecutionWorkflowPlan plan = plan();
        service.completeCheckpoint(41L, plan, "plan", "{\"cursor\":1,\"message\":\"开始\"}");
        service.completeCheckpoint(41L, plan, "execute", "{\"cursor\":2}");

        context.close();
        context = openContext(dataSource);
        ExecutionCheckpointService restartedProcess = context.getBean(ExecutionCheckpointService.class);
        ExecutionResumeState restored = restartedProcess.resume(41L, plan);

        assertTrue(AopUtils.isAopProxy(restartedProcess));
        assertEquals(List.of("plan", "execute"), restored.completedStepKeys());
        assertEquals("{\"cursor\":1,\"message\":\"开始\"}",
                restored.acceptedCheckpoints().get(0).stateJson());
        assertEquals(List.of("checkpoint"), restored.executableStepKeys());
        assertFalse(restored.complete());
        restartedProcess.completeCheckpoint(41L, plan, "execute", "{\"cursor\":2}");
        assertEquals(2, count("execution_checkpoints", 41L));

        jdbcTemplate.update("delete from execution_checkpoints where task_id = ? and sequence_no = ?", 41L, 1);
        ExecutionCheckpointIntegrityException truncated = assertThrows(
                ExecutionCheckpointIntegrityException.class,
                () -> restartedProcess.resume(41L, plan)
        );
        assertEquals("CHECKPOINT_HEAD_COUNT_DRIFT", truncated.getReasonCode());

        jdbcTemplate.update("delete from execution_checkpoints where task_id = ?", 41L);
        ExecutionCheckpointIntegrityException fullyTruncated = assertThrows(
                ExecutionCheckpointIntegrityException.class,
                () -> restartedProcess.resume(41L, plan)
        );
        assertEquals("CHECKPOINT_HEAD_COUNT_DRIFT", fullyTruncated.getReasonCode());
    }

    @Test
    void realMigration_shouldEnforceParentAndUniquenessConstraints() {
        service.completeCheckpoint(41L, plan(), "plan", "{}");

        assertThrows(Exception.class, () -> jdbcTemplate.update("""
                insert into execution_checkpoints
                    (task_id, task_binding_sha256, workflow_id, workflow_sha256, sequence_no, step_key,
                     input_sha256, state_json, state_byte_length, state_sha256, status)
                select task_id, task_binding_sha256, workflow_id, workflow_sha256, sequence_no, 'other',
                       input_sha256, state_json, state_byte_length, state_sha256, status
                from execution_checkpoints where task_id = 41
                """));
        assertThrows(Exception.class, () -> jdbcTemplate.update("""
                insert into execution_checkpoints
                    (task_id, task_binding_sha256, workflow_id, workflow_sha256, sequence_no, step_key,
                     input_sha256, state_json, state_byte_length, state_sha256, status)
                values (999, ?, 'agent-run-v1', ?, 0, 'plan', ?, '{}', 2, ?, 'COMPLETED')
                """, "a".repeat(64), "b".repeat(64), "c".repeat(64), "d".repeat(64)));
        assertThrows(Exception.class,
                () -> jdbcTemplate.update("delete from execution_tasks where id = ?", 41L));
    }

    @Test
    void concurrentConflictingCompletion_shouldSerializeAndAcceptExactlyOneState() throws Exception {
        ExecutorService executor = Executors.newFixedThreadPool(2);
        try {
            CountDownLatch start = new CountDownLatch(1);
            Future<String> first = executor.submit(() -> completeAfter(start, "{\"winner\":1}"));
            Future<String> second = executor.submit(() -> completeAfter(start, "{\"winner\":2}"));
            start.countDown();

            List<String> results = List.of(first.get(), second.get());
            assertEquals(1, results.stream().filter("ACCEPTED"::equals).count());
            assertEquals(1, results.stream().filter("CONFLICTING_CHECKPOINT_REWRITE"::equals).count());
            assertEquals(1, count("execution_checkpoints", 41L));
            assertEquals(1, count("execution_checkpoint_heads", 41L));
        } finally {
            executor.shutdownNow();
        }
    }

    @Test
    void missingTaskAndMovedRows_shouldFailClosed() {
        ExecutionCheckpointIntegrityException missing = assertThrows(
                ExecutionCheckpointIntegrityException.class,
                () -> service.resume(99L, plan())
        );
        assertEquals("TASK_NOT_FOUND", missing.getReasonCode());

        service.completeCheckpoint(41L, plan(), "plan", "{}");
        jdbcTemplate.update("insert into execution_tasks (id, status) values (?, ?)", 42L, "RUNNING");
        jdbcTemplate.update("update execution_checkpoints set task_id = ? where task_id = ?", 42L, 41L);
        ExecutionCheckpointIntegrityException moved = assertThrows(
                ExecutionCheckpointIntegrityException.class,
                () -> service.resume(42L, plan())
        );
        assertEquals("CHECKPOINT_HEAD_MISSING", moved.getReasonCode());
    }

    private String completeAfter(CountDownLatch start, String stateJson) throws InterruptedException {
        start.await();
        try {
            service.completeCheckpoint(41L, plan(), "plan", stateJson);
            return "ACCEPTED";
        } catch (ExecutionCheckpointIntegrityException error) {
            return error.getReasonCode();
        }
    }

    private int count(String table, Long taskId) {
        Integer count = jdbcTemplate.queryForObject(
                "select count(*) from " + table + " where task_id = ?", Integer.class, taskId
        );
        return count == null ? 0 : count;
    }

    private AnnotationConfigApplicationContext openContext(DataSource source) {
        AnnotationConfigApplicationContext applicationContext = new AnnotationConfigApplicationContext();
        JdbcTemplate template = new JdbcTemplate(source);
        ExecutionCheckpointStore store = new ExecutionCheckpointStore(template);
        applicationContext.register(TransactionConfiguration.class);
        applicationContext.registerBean(DataSource.class, () -> source);
        applicationContext.registerBean(JdbcTemplate.class, () -> template);
        applicationContext.registerBean(PlatformTransactionManager.class,
                () -> new DataSourceTransactionManager(source));
        applicationContext.registerBean(ExecutionCheckpointStore.class, () -> store);
        applicationContext.registerBean(ExecutionCheckpointService.class,
                () -> new ExecutionCheckpointService(store));
        applicationContext.refresh();
        return applicationContext;
    }

    private ExecutionWorkflowPlan plan() {
        return new ExecutionWorkflowPlan("agent-run-v1", List.of(
                new ExecutionPlanStep("plan", "a".repeat(64)),
                new ExecutionPlanStep("execute", "b".repeat(64)),
                new ExecutionPlanStep("checkpoint", "c".repeat(64))
        ));
    }

    @Configuration(proxyBeanMethods = false)
    @EnableTransactionManagement(proxyTargetClass = true)
    static class TransactionConfiguration {
    }
}
