package com.sourcelens;

import com.sourcelens.module.execution.dto.ExecutionPlanStep;
import com.sourcelens.module.execution.dto.ExecutionResumeState;
import com.sourcelens.module.execution.dto.ExecutionWorkflowPlan;
import com.sourcelens.module.execution.mapper.ExecutionCheckpointStore;
import com.sourcelens.module.execution.service.ExecutionCheckpointIntegrityException;
import com.sourcelens.module.execution.service.ExecutionCheckpointService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ExecutionCheckpointH2IntegrationTest {

    private JdbcTemplate jdbcTemplate;
    private ExecutionCheckpointStore store;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:p3_checkpoint_" + UUID.randomUUID() + ";MODE=MYSQL;DB_CLOSE_DELAY=-1",
                "sa", ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                create table execution_tasks (
                    id bigint generated by default as identity primary key,
                    status varchar(20) not null
                )
                """);
        jdbcTemplate.execute("""
                create table execution_checkpoints (
                    id bigint generated by default as identity primary key,
                    task_id bigint not null,
                    workflow_id varchar(120) not null,
                    workflow_sha256 char(64) not null,
                    sequence_no int not null,
                    step_key varchar(120) not null,
                    input_sha256 char(64) not null,
                    state_json clob not null,
                    state_byte_length bigint not null,
                    state_sha256 char(64) not null,
                    status varchar(20) not null,
                    created_at timestamp not null default current_timestamp,
                    updated_at timestamp not null default current_timestamp,
                    constraint uk_checkpoint_sequence unique (task_id, sequence_no),
                    constraint uk_checkpoint_step unique (task_id, step_key)
                )
                """);
        jdbcTemplate.update("insert into execution_tasks (id, status) values (?, ?)", 41L, "RUNNING");
        store = new ExecutionCheckpointStore(jdbcTemplate);
    }

    @Test
    void freshService_shouldRestoreExactPrefixAndRejectPersistedDrift() {
        ExecutionWorkflowPlan plan = plan();
        ExecutionCheckpointService firstProcess = new ExecutionCheckpointService(store);
        firstProcess.completeCheckpoint(41L, plan, "plan", "{\"cursor\":1,\"message\":\"开始\"}");
        firstProcess.completeCheckpoint(41L, plan, "execute", "{\"cursor\":2}");

        ExecutionCheckpointService restartedProcess = new ExecutionCheckpointService(
                new ExecutionCheckpointStore(jdbcTemplate)
        );
        ExecutionResumeState restored = restartedProcess.resume(41L, plan);

        assertEquals(List.of("plan", "execute"), restored.completedStepKeys());
        assertEquals("{\"cursor\":1,\"message\":\"开始\"}",
                restored.acceptedCheckpoints().get(0).stateJson());
        assertEquals(List.of("checkpoint"), restored.executableStepKeys());
        assertFalse(restored.complete());
        restartedProcess.completeCheckpoint(41L, plan, "execute", "{\"cursor\":2}");
        assertEquals(2, jdbcTemplate.queryForObject(
                "select count(*) from execution_checkpoints where task_id = ?", Integer.class, 41L
        ));

        jdbcTemplate.update("update execution_checkpoints set state_json = ? where task_id = ? and sequence_no = 0",
                "{\"cursor\":999}", 41L);
        ExecutionCheckpointIntegrityException error = assertThrows(
                ExecutionCheckpointIntegrityException.class,
                () -> restartedProcess.resume(41L, plan)
        );
        assertEquals("STATE_INTEGRITY_DRIFT", error.getReasonCode());
    }

    @Test
    void databaseConstraints_shouldRejectDuplicateSequenceAndStep() {
        ExecutionCheckpointService service = new ExecutionCheckpointService(store);
        service.completeCheckpoint(41L, plan(), "plan", "{}");

        assertThrows(Exception.class, () -> jdbcTemplate.update("""
                insert into execution_checkpoints
                    (task_id, workflow_id, workflow_sha256, sequence_no, step_key,
                     input_sha256, state_json, state_byte_length, state_sha256, status)
                select task_id, workflow_id, workflow_sha256, sequence_no, 'other',
                       input_sha256, state_json, state_byte_length, state_sha256, status
                from execution_checkpoints where task_id = 41
                """));
        assertThrows(Exception.class, () -> jdbcTemplate.update("""
                insert into execution_checkpoints
                    (task_id, workflow_id, workflow_sha256, sequence_no, step_key,
                     input_sha256, state_json, state_byte_length, state_sha256, status)
                select task_id, workflow_id, workflow_sha256, 1, step_key,
                       input_sha256, state_json, state_byte_length, state_sha256, status
                from execution_checkpoints where task_id = 41
                """));
    }

    private ExecutionWorkflowPlan plan() {
        return new ExecutionWorkflowPlan("agent-run-v1", List.of(
                new ExecutionPlanStep("plan", "a".repeat(64)),
                new ExecutionPlanStep("execute", "b".repeat(64)),
                new ExecutionPlanStep("checkpoint", "c".repeat(64))
        ));
    }
}
